# Generated by Django 3.2 on 2022-10-16 17:24

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IEHPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('iehp_id', models.CharField(max_length=255)),
                ('appointment_date', models.CharField(max_length=25)),
                ('requesting_provider', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('icd_1', models.CharField(max_length=255)),
                ('lens_cpt_1', models.CharField(max_length=255)),
                ('frame_cpt_1', models.CharField(max_length=255)),
                ('confirmation_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticalPIAOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subscriber_id', models.CharField(max_length=255)),
                ('subscriber_birthdate', models.CharField(max_length=255)),
                ('service_date', models.CharField(max_length=255)),
                ('issue_date', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=255)),
                ('focal_options', models.CharField(max_length=255)),
                ('sphere_r', models.CharField(max_length=255)),
                ('sphere_l', models.CharField(max_length=255)),
                ('cylinder_r', models.CharField(max_length=255)),
                ('cylinder_l', models.CharField(max_length=255)),
                ('axis_l', models.CharField(max_length=255)),
                ('axis_r', models.CharField(max_length=255)),
                ('pupillary_far_r', models.CharField(max_length=255)),
                ('pupillary_far_l', models.CharField(max_length=255)),
                ('pupillary_near_l', models.CharField(max_length=255)),
                ('pupillary_near_r', models.CharField(max_length=255)),
                ('add_power_r', models.CharField(max_length=255)),
                ('add_power_l', models.CharField(max_length=255)),
                ('seg_height_l', models.CharField(max_length=255)),
                ('seg_height_r', models.CharField(max_length=255)),
                ('oc_height_l', models.CharField(max_length=255)),
                ('oc_height_r', models.CharField(max_length=255)),
                ('frame_enclosed', models.CharField(max_length=255)),
                ('frame_manufacturer', models.CharField(max_length=255)),
                ('frame_style', models.CharField(max_length=255)),
                ('eye_size', models.CharField(max_length=255)),
                ('bridge_size', models.CharField(max_length=255)),
                ('temple_size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('frame_type', models.CharField(max_length=255)),
                ('confirmation_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploaded-pdf/optical-pia/')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
