# Generated by Django 3.2 on 2022-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalpiaorder',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
