version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - optics_rpa

x-django-build: &django-build
  build:
    context: .
    dockerfile: Dockerfile.stage

services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210929
    container_name: optics_rpa-sh
    ports:
      - "4444:4444"
    <<: *common

  chrome:
    image: selenium/node-chrome:3.141.59-20210929
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=20
      - NODE_MAX_SESSION=20
    links:
      - selenium-hub
    <<: *common

  django:
    <<: *django-build
    container_name: optics_rpa-dc-01
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
      - optics_rpa_static_volume:/code/static
      - optics_rpa_media_volume:/code/media
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - chrome
    <<: *common

  celery:
    <<: *django-build
    container_name: optics_rpa-cc-01
    restart: always
    command: bash -c "celery -A config worker -l info"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
      - django
      - redis
    <<: *common

  celery-beat:
    <<: *django-build
    container_name: optics_rpa-cb-01
    command: bash -c "celery -A config worker -l info --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - postgres
      - django
      - redis
    env_file:
      - ./.env
    volumes:
      - .:/code/
    <<: *common

  flower:
    image: mher/flower:0.9.7
    container_name: optics_rpa-fc01
    restart: unless-stopped
    command:
      [
        "flower",
        "--broker=redis://redis:6379/0",
        "--broker_api=redis://redis:6379/0",
        "--port=5555",
      ]
    ports:
      - "5555:5555"
    <<: *common

  redis:
    image: redis
    container_name: optics_rpa-rc01
    volumes:
      - optics_rpa_redis_data:/data
    ports:
      - "6379:6379"
    <<: *common

  postgres:
    image: postgres:13.3-alpine
    container_name: optics_rpa-pc01
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - optics_rpa_postgres_data:/var/lib/postgresql/data/
    <<: *common

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: optics_rpa-nc01
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/stage.conf:/etc/nginx/conf.d/default.conf
      - optics_rpa_static_volume:/code/static
      - optics_rpa_media_volume:/code/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    <<: *common

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  optics_rpa:
    driver: bridge


volumes:
  optics_rpa_postgres_data:
  optics_rpa_redis_data:
  optics_rpa_static_volume:
  optics_rpa_media_volume:
