# Generated by Django 3.2 on 2022-09-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEHPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iehp_id', models.CharField(max_length=255)),
                ('service_priority', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('services_requested', models.CharField(max_length=255)),
                ('icd_1', models.CharField(max_length=255)),
                ('materials_services', models.CharField(max_length=255)),
                ('material_options', models.CharField(max_length=255)),
                ('lens_cpt_1', models.CharField(max_length=255)),
                ('lens_qty', models.CharField(max_length=255)),
                ('frame_cpt_1', models.CharField(max_length=255)),
                ('frame_qty', models.CharField(max_length=255)),
            ],
        ),
    ]
