# Generated by Django 3.2 on 2022-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0002_iehporder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iehporder',
            old_name='frame_qty',
            new_name='requesting_provider',
        ),
        migrations.RemoveField(
            model_name='iehporder',
            name='lens_qty',
        ),
        migrations.RemoveField(
            model_name='iehporder',
            name='material_options',
        ),
        migrations.RemoveField(
            model_name='iehporder',
            name='materials_services',
        ),
        migrations.RemoveField(
            model_name='iehporder',
            name='service_priority',
        ),
        migrations.RemoveField(
            model_name='iehporder',
            name='services_requested',
        ),
        migrations.AddField(
            model_name='iehporder',
            name='appointment_date',
            field=models.CharField(default='n/a', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iehporder',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
