# Generated by Django 3.2 on 2022-08-14 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('PENDING', 'Pending')], default='PENDING', max_length=25)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticalPIAOrderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='optical-screenshot1/%Y/%m/')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='optical-screenshot2/%Y/%m/')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('PENDING', 'Pending')], default='PENDING', max_length=255)),
                ('optical_pia_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpa.opticalpiaorder')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.submission')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
