# Generated by Django 3.2 on 2022-08-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
        ('submissions', '0003_testimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImageModel',
        ),
        migrations.AddField(
            model_name='opticalpiaordersubmission',
            name='error_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='error-screenshot/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='opticalpiaordersubmission',
            name='error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opticalpiaordersubmission',
            name='optical_pia_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='rpa.opticalpiaorder'),
        ),
    ]
