# Generated by Django 3.2 on 2022-08-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20220823_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalpiaordersubmission',
            name='error_text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
