# Generated by Django 3.2 on 2022-09-11 17:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0002_iehporder'),
        ('submissions', '0006_alter_opticalpiaordersubmission_error_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('OPTICAL_PIA', 'Optical PIA'), ('IEHP', 'IEHP')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IEHPOrderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='iehp-screenshot1/%Y-%m/')),
                ('error_screenshot', models.ImageField(blank=True, null=True, upload_to='error-screenshot/%Y-%m/')),
                ('error_text', models.CharField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('PENDING', 'Pending')], default='PENDING', max_length=255)),
                ('iehp_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='rpa.iehporder')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.submission')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
